import type { Metadata } from 'next';
import { Goblin_One, EB_Garamond } from 'next/font/google';
import './globals.css';

const goblinOne = Goblin_One({
  variable: '--font-goblin-one',
  subsets: ['latin'],
  weight: '400'
  // TODO fallback
});

const garamond = EB_Garamond({
  variable: '--font-garamond',
  subsets: ['latin'],
  weight: ['400', '700', '800']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${goblinOne.variable} ${garamond.variable}`}>
        {children}
      </body>
    </html>
  );
}
